### ISSUE TITLE
OpenAPI specs incomplete for most APIs

### ISSUE THREAD

**Issue by alex1987** [hmrc/income-tax-mtd-changelog#318]
I've found the published OpenAPI YAML specs to be incomplete for most APIs.

For example, for Individuals Other Income (2.0), the web version is complete as expected
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individuals-other-income-api/2.0/oas/page
but when downloading the YAML file from the "Download OpenAPI specification" link
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individuals-other-income-api/2.0/oas/resolved

It only contains `summary` and `security` for each endpoint
```
paths:
  /individuals/other-income/{nino}/{taxYear}:
    get:
      summary: Retrieve Other Income
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Other Income
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Other Income
      security:
      - User-Restricted:
        - write:self-assessment
```
It's missing `description`, `parameters`, `requestBody`, `responses` etc.

From looking at the source files e.g. https://github.com/hmrc/individuals-other-income-api/blob/main/resources/public/api/conf/2.0/other.yaml it seems like this may result from an issue with certain `$ref`s not being followed when generating the resolved version.

The full list of APIs I've found to have incomplete specs:
(most are similar to the Other Income example, some do have partial or full specs for some endpoints but missing for others)
* Individuals Savings Income (1.0)
* Individuals Capital Gains Income (2.0)
* Individuals Foreign Income (2.0)
* Individuals Dividends Income (2.0)
* Individuals Insurance Policies Income (2.0)
* Individuals Pensions Income (2.0)
* Individuals State Benefits (2.0)
* Individuals Other Income (2.0)
* Individuals Expenses (3.0)
* Individuals Charges (3.0)
* Individuals Disclosures (2.0)
* Individuals Reliefs (2.0)
* Other Deductions (2.0)

These seem to be complete:
* Individuals Employments Income (1.0)
* CIS Deductions (3.0)
* Individual Calculations (7.0)
* Individual Losses (6.0)
